config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  get 'pages/home'
  get 'next-step', to: 'pages#next_step'
  get 'work', to: 'pages#work'
  get 'about', to: 'pages#about'
  get 'send-a-message', to: 'pages#message'
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def create
    @contact = Contact.create(contact_params)
    if verify_recaptcha(@contact) && @contact.save
      ContactMailer.new_submission_email(@contact).deliver
      ContactMailer.thank_you_email(@contact).deliver
      redirect_to root_path
      flash[:notice] = "Your message has been sent."
    else
      redirect_to root_path
      flash[:notice] = "Your email did not go through, please try again."
    end

    # if @contact.save
    #   ContactMailer.new_submission_email(@contact).deliver
    #   ContactMailer.thank_you_email(@contact).deliver
    #   redirect_to root_path
    # end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :phone, :message)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def next_step
    @contact = Contact.new
  end

  def about
  end

  def work
  end

  def message
    @contact = Contact.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bigmoondev</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
  </head>

  <body>
    <% if notice %>
    <div id="notice_wrapper">
      <p class="notice"><%= notice %></p>
    </div>
    <% elsif alert %>
      <div id="alert_wrapper">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <%= yield %>

    <script>
      $(document).ready(function() {
        setTimeout(function() {
          $('#notice_wrapper').fadeOut("slow", function() {
            $(this).remove();
          })
        }, 3500);
      });
    </script>
  </body>
</html>

app/views/pages/about.html.erb
<%= render 'partials/navbar-dark' %>

<main>
  <div class="container">
    <div class="about">
      <div class="row">
        <div class="col-md-12">
          <h1 class="about__header">We are Big Moon!</h1>
          <div class="about__img-container">
            <div class="about_img-box">
              <%= image_tag 'aaron.png', class: 'about__img' %>
              <p class="about__img-info"><span class="info-name">Aaron Johnson</span><br/><span class="info-title">Founder, Development & Design</span></p>
            </div>
            <div class="about_img-box">
              <%= image_tag 'dustin.png', class: 'about__img' %>
              <p class="about__img-info"><span class="info-name">Dustin Smith</span><br/><span class="info-title">Development & Design</div></p>
            </div>
          </div>
          <h2 class="about__subheader">We enjoy using these technologies:</h2>
          <div class="row">
            <div class="col-md-offset-2 col-md-8">
              <div class="tech">
                <%= image_tag 'wordpress.svg', class: 'tech__img' %>
                <%= image_tag 'rails.svg', class: 'tech__img' %>
                <%= image_tag 'html5.png', class: 'tech__img' %>
                <!-- tech__img-spin for rotating icon -->
                <%= image_tag 'react.svg', class: 'tech__img' %>
                <%= image_tag 'meteor.svg', class: 'tech__img' %>
                <!-- <%= image_tag 'node.svg', class: 'tech__img' %> -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>


<%= render 'partials/footer' %>

app/views/pages/contact.html.erb
<%= render 'partials/navbar-dark' %>


<main>
  <div class="container">
    <div class="next_step">
      <div class="row">
        <div class="col-md-12">
          <h1 class="next_step__header">Hey! Would love to hear from you!</h1>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6">
          <p class="next_step__sub">Fill out the form below with your name, contact info, and a description of the your project and we will be in touch.</p>
          <form class="info_form">
            <input type="text" placeholder="Name" class="info_form__input" />
            <input type="text" placeholder="Email" class="info_form__input" />
            <input type="text" placeholder="Phone" class="info_form__input" />
            <textarea placeholder="Tell us about your project" class="info_form__textarea"></textarea>
            <button class="info_form__button">Send Message</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>


<%= render 'partials/footer' %>

app/views/pages/home.html.erb
<%= render 'partials/navbar' %>

<header class="home_header">
  <h1 class="home_header__headline">Let's build something great!</h1>
  <p class="home_header__text"><%= link_to "Get Started", next_step_path, class: 'home_header__get-started-btn' %></p>
</header>

<%= render 'partials/footer' %>

app/views/pages/message.html.erb
<%= render 'partials/navbar-dark' %>


<main>
  <div class="container">
    <div class="next_step">
      <div class="row">
        <div class="col-md-12">
          <h1 class="next_step__header">Hey! Would love to hear from you!</h1>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6">
          <p class="next_step__sub">Fill out the form below with your name, contact info, and a description of the your project and we will be in touch.</p>

          <%= form_for @contact do |f| %>
            <%= f.text_field :name, class: 'info_form__input', placeholder: 'Name' %>
            <%= f.text_field :email, class: 'info_form__input', placeholder: 'Email' %>
            <%= f.text_field :phone, class: 'info_form__input', placeholder: 'Phone' %>
            <%= f.text_area :message, class: 'info_form__textarea', placeholder: 'Tell us about your project' %>
            <div class="recaptcha">
              <%= recaptcha_tags %>
            </div>
            <%= f.submit 'Send Message', class: 'info_form__button' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>


<%= render 'partials/footer' %>

app/views/pages/next_step.html.erb
<%= render 'partials/navbar-dark' %>


<main>
  <div class="container">
    <div class="next_step">
      <div class="row">
        <div class="col-md-12">
          <h1 class="next_step__header">Awesome! You have taken the first step.</h1>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6">
          <p class="next_step__sub">Now fill out the form below with your name, contact info, and a description of the your project and we will be in touch.</p>
          <%= form_for @contact do |f| %>
            <%= f.text_field :name, class: 'info_form__input', placeholder: 'Name' %>
            <%= f.text_field :email, class: 'info_form__input', placeholder: 'Email' %>
            <%= f.text_field :phone, class: 'info_form__input', placeholder: 'Phone' %>
            <%= f.text_area :message, class: 'info_form__textarea', placeholder: 'Tell us about your project' %>
            <div class="recaptcha">
              <%= recaptcha_tags %>
            </div>
            <%= f.submit 'Send Message', class: 'info_form__button' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>


<%= render 'partials/footer' %>

app/views/pages/work.html.erb
<%= render 'partials/navbar-dark' %>

<main>
  <div class="container">
    <div class="work">
      <div class="row">
        <div class="col-md-12">
          <h1 class="work__header">Some of our work</h1>

          <div class="col-xs-offset-0 col-xs-12 col-sm-offset-0 col-sm-12 col-md-offset-2 col-md-8 col-lg-offset-2 col-lg-8">
            <div class="iphone">
              <div class="iphone__image">
                <%= image_tag 'iphone.png', class: 'iphone__img' %>
              </div>
              <div class="iphone__content">
                <h2 class="iphone__title">Let's Go Ride</h2>
                <p class="iphone__description">Let'Go Ride is a cycling app designed with simplicity in mind. It was developed with a focus on a small set of metrics that the average rider is most concerned with, such as distance, time, speed, average speed, and elevation gained.</p>
                <%= link_to image_tag('app_store.png', class: 'app_store'), 'https://itunes.apple.com/us/app/lets-go-ride/id1226006817?mt=8' %>
                <p class="web__tech"><span>Technology:</span> iOS, Swift</p>
              </div>
            </div>
          </div>



          <div class="col-xs-offset-0 col-xs-12 col-sm-offset-0 col-sm-12 col-md-offset-0 col-md-12 col-lg-offset-1 col-lg-10">

            <div class="web_top">
              <div class="web__display">
                <%= image_tag 'iam_sample.png', class: 'web__img' %>
              </div>
              <div class="web__content">
                <h2 class="web__title">I Am Worship Church</h2>
                <p class="web__description">I Am Worship Church is a church plant that desired a site that would engage potential visitors when they visited the site. To achieve this we designed a landing page that delivered all essential content, and provided clear navigation to additional content that may be of interest. We also wanted to make sure that current attendees could access the site quickly and easily for important information.</p>
                <p class="web__link"><%= link_to 'View Website', 'http://iamworshipchurch.com', class: 'web__link-a' %></p>
                <p class="web__tech"><span>Technology:</span> Wordpress, Twitter Bootstrap</p>
              </div>
            </div>

            <div class="web_alt">
              <div class="web__display">
                <%= image_tag 'untie_sample.png', class: 'web__img' %>
              </div>
              <div class="web_alt__content">
                <h2 class="web__title">Chadwick and Tignor</h2>
                <p class="web__description">Client was seeking a dynamic site to onboard potential clients for packaged services. We achieved this by providing a site where the user was easily and clearly guided through the process of seeking counsel.</p>
                <p class="web__link"><%= link_to 'View Website', 'http://untietheknottn.com', class: 'web__link-a' %></p>
                <p class="web__tech"><span>Technology:</span> Ruby on Rails, Twitter Bootstrap</p>
              </div>
            </div>

            <div class="web_bottom">
              <div class="web__display">
                <%= image_tag 'mercy_sample.png', class: 'web__img' %>
              </div>
              <div class="web__content">
                <h2 class="web__title">Mercy Fellowship</h2>
                <p class="web__description">Mercy Fellowship is a church plant that desired a site that would appeal to prospects in a very down to earth, low-key way, but with theological truth. This site was developed in Wordpress to allow them to have control over the content of the site.</p>
                <p class="web__link"><%= link_to 'View Website', 'http://mercynashville.org', class: 'web__link-a' %></p>
                <p class="web__tech"><span>Technology:</span> Wordpress, Twitter Bootstrap</p>
              </div>
            </div>




          </div>



          <!-- <%= image_tag 'mercy_sample.png', class: 'web' %>
          <%= image_tag 'untie_sample.png', class: 'web' %> -->


        </div>
      </div>
    </div>
  </div>
</main>

<%= render 'partials/footer' %>

app/views/partials/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="footer">
          <p class="footer__text">&copy; Big Moon</p>
          <p class="footer__text">contact@bigmoondev.com | 615-630-5540</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/partials/_navbar-dark.html.erb
<!-- <nav class="nav">
  <div class="navbar">
    <%= link_to image_tag("logo.svg", alt: "Logo", class: "logo_img"), root_path %>
    <ul class="navbar__list">
      <li class="navbar__list-item">About</li>
      <li class="navbar__list-item">Work</li>
      <li class="navbar__list-item">Blog</li>
      <li class="navbar__list-item">Contact</li>
    </ul>
  </div>
</nav> -->

<nav class="navbar navbar-dark">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigationBar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= image_tag 'logo_white.png', class: 'logo_img' %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navigationBar">
      <!-- <ul class="nav navbar-nav"></ul> -->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Work', work_path %></li>
        <!-- <li><a href="#">Blog</a></li> -->
        <li><%= link_to 'Contact', send_a_message_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_navbar-orange.html.erb
<!-- <nav class="nav">
  <div class="navbar">
    <%= link_to image_tag("logo.svg", alt: "Logo", class: "logo_img"), root_path %>
    <ul class="navbar__list">
      <li class="navbar__list-item">About</li>
      <li class="navbar__list-item">Work</li>
      <li class="navbar__list-item">Blog</li>
      <li class="navbar__list-item">Contact</li>
    </ul>
  </div>
</nav> -->

<nav class="navbar navbar-orange">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= image_tag 'logo_alt2.png', class: 'logo_img' %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- <ul class="nav navbar-nav"></ul> -->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Work', work_path %></li>
        <!-- <li><a href="#">Blog</a></li> -->
        <li><%= link_to 'Contact', send_a_message_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_navbar.html.erb
<!-- <nav class="nav">
  <div class="navbar">
    <%= link_to image_tag("logo.svg", alt: "Logo", class: "logo_img"), root_path %>
    <ul class="navbar__list">
      <li class="navbar__list-item">About</li>
      <li class="navbar__list-item">Work</li>
      <li class="navbar__list-item">Blog</li>
      <li class="navbar__list-item">Contact</li>
    </ul>
  </div>
</nav> -->

<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= image_tag 'logo.png', class: 'logo_img' %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- <ul class="nav navbar-nav"></ul> -->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Work', work_path %></li>
        <!-- <li><a href="#">Blog</a></li> -->
        <li><%= link_to 'Contact', send_a_message_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>